### ISSUE TITLE
ติดตั้งแล้วเรียกใช้

### ISSUE THREAD

**Issue by fvck3oy** [Fortune-Inc/tw-voucher#6]
TypeError: fetch is not a function

**Comment by pp0236** [comment]
ต้อง update nodejs ให้เป็น version **16.5+** ครับ
api ไม่ support
![image_2022-05-20_182940861](https://user-images.githubusercontent.com/54238880/169519507-ac806836-68fb-4307-b409-621ba123117a.png)

**Comment by fvck3oy** [comment]
ขอบคุณมากครับผม
